### PR TITLE
kmod/core: fix stacktrace_ops 'address' function prototype for 4.6

### LINKED ISSUE #584: Recent struct stacktrace_ops change breaks kpatch core module
The kpatch core module currently breaks with linux-next. A recent commit upstream (568b329a "perf: generalize perf_callchain") modifies the `struct stacktrace_ops` declaration in arch/x86/include/asm/stacktrace.h. This issue **doesn't** apply to the current 4.5 kernel release, so just noting for now that this might have to be fixed for 4.6.
````
./kpatch/kmod/core/core.c:255:13: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .address = kpatch_backtrace_address_verify,
             ^
./kpatch/kmod/core/core.c:255:13: note: (near initialization for ‘kpatch_backtrace_ops.address’)
./kpatch/kmod/core/core.c:275:13: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .address = kpatch_print_trace_address,
```

### PR DESCRIPTION
**Pull request by flaming-toast**
Fixes #584.

Since `kpatch_backtrace_address_verify` returns an int now, `args->ret` isn't used in the new version, since returning an error will prompt `print_context_stack_bp` to stop walking the stack. Tested on 4.5.0 and 4.6.0-rc5.

### CODE REVIEW

File: kmod/core/core.c [hunk 1]
```diff
@@ -195,6 +195,7 @@ static inline int kpatch_compare_addresses(unsigned long stack_addr,
 	return 0;
 }
 
+#if LINUX_VERSION_CODE <= KERNEL_VERSION(4, 5, 0)
```
Comment (jpoimboe) [inline kmod/core/core.c]: Would this break with a kernel 4.5.1?

Maybe it would better to say `#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 6, 0)`.  Not sure if that would exclude the 4.6-rcX releases, but we don't need to support them anyway.

File: kmod/core/core.c [hunk 2]
```diff
@@ -264,12 +318,23 @@ static int kpatch_print_trace_stack(void *data, char *name)
...
```
Comment (jpoimboe) [inline kmod/core/core.c]: Same here.

File: kmod/core/core.c (hunk 1 above)
Comment (flaming-toast) [inline kmod/core/core.c]: Ah yeah, you are right.
